services:
  sniplockr-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: sniplockr-dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    environment:
      - NODE_ENV=development

